### ISSUE TITLE
Can't instantiate abstract class with abstract methods create

### ISSUE THREAD

**Issue by regner** [Sysnove/flask-servicelayer#2]
It appears the create method is defined as an abstractmethod on the base service class but not implemented in either the SQLAlchemyService or LDAPOMService services. This results in a TypeError when trying to instantiate a service based off of these due to create not being defined in any of the sub classes.

It seems like either create should be defined in both SQLAlchemyService and LDAPOMService or made to not be an abstractmethod.

``` bash
regner:~/workspace $ python manage.py update_capsuleers
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    from evepilots.capsuleers.scripts import UpdateExistingCapsuleers, LoadCapsuleers
  File "/home/ubuntu/workspace/evepilots/capsuleers/scripts.py", line 5, in <module>
    from evepilots.capsuleers.utils import update_capsuleers, load_capsuleers_file
  File "/home/ubuntu/workspace/evepilots/capsuleers/utils.py", line 9, in <module>
    from evepilots.services import capsuleers
  File "/home/ubuntu/workspace/evepilots/services.py", line 5, in <module>
    capsuleers = CapsuleerService()
TypeError: Can't instantiate abstract class CapsuleerService with abstract methods create
```

**Comment by maethor** [comment]
Thank you very much. It's very odd because I don't have this bug, and all my apps and unit tests are working just fine. But I agree, this method should not be abstract. I fixed the bug and pushed the new version to pypi.

And thank you for using this lib :-)

**Comment by regner** [comment]
Thanks for taking care of that so quickly.
